package com.bakery.config;

import com.bakery.model.MenuItem;
import com.bakery.model.MenuItemRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import java.util.List;

@Component
public class MenuSeeder implements CommandLineRunner {

    private final MenuItemRepository repo;

    public MenuSeeder(MenuItemRepository repo) {
        this.repo = repo;
    }

    @Override
    public void run(String... args) {
        if (repo.count() > 0) {
            return;
        }

        List<MenuItem> items = List.of(
        new MenuItem("cuban-sandwich", "Sándwich Cubano", "Cuban Sandwich",
            "Sandwiches", "Sandwiches",
            "Jamón, pernil asado, queso suizo, pepinillos y mostaza en pan crujiente.",
            "Ham, roasted pork, Swiss cheese, pickles, and mustard on crispy bread.",
            "Pan cubano, jamón, pernil asado, queso suizo, pepinillos, mostaza",
            "Cuban bread, ham, roasted pork, Swiss cheese, pickles, mustard",
            "$9.50", "/img/menu-cuban-sandwich.jpg", true, 1),

        new MenuItem("bacon-egg-cheese", "Sándwich de Bacon, Huevo y Queso", "Bacon, Egg and Cheese Sandwich",
            "Sandwiches", "Sandwiches",
            "Bacon crujiente, huevo derretido y queso fundido en pan tostado (americano o suizo).",
            "Crisp bacon, melted egg, and melted cheese on toasted bread (American or Swiss).",
            "Pan tostado, bacon, huevo, queso americano o suizo",
            "Toasted bread, bacon, egg, American or Swiss cheese",
            "$8.75", "/img/menu-bacon-egg-cheese.jpg", true, 2),

        new MenuItem("media-noche", "Sándwich Media Noche", "Media Noche Cuban Sandwich",
            "Sandwiches", "Sandwiches",
            "Jamón, pernil asado, queso suizo, pepinillos y mostaza en pan dulce suave.",
            "Ham, roasted pork, Swiss cheese, pickles, and mustard on soft sweet bread.",
            "Pan suave, jamón, pernil asado, queso suizo, pepinillos, mostaza",
            "Sweet bread, ham, roasted pork, Swiss cheese, pickles, mustard",
            "$9.00", "/img/menu-media-noche.jpg", false, 3),

        new MenuItem("bread-butter", "Pan con Mantequilla", "Bread with Butter",
            "Sandwiches", "Sandwiches",
            "Pan caliente recién horneado con una generosa capa de mantequilla cremosa.",
            "Warm, freshly baked bread paired with a generous spread of creamy butter.",
            "Pan cubano, mantequilla",
            "Cuban bread, butter",
            "$2.80", "/img/menu-bread-butter.jpg", false, 4),

        new MenuItem("egg-ham-cheese", "Sándwich de Huevo, Jamón y Queso", "Egg, Ham and Cheese Sandwich",
            "Sandwiches", "Sandwiches",
            "Combinación clásica de huevo, jamón y queso derretido en pan tostado.",
            "Classic combination of egg, ham, and melted cheese on toasted bread.",
            "Pan tostado, huevo, jamón, queso",
            "Toasted bread, egg, ham, cheese",
            "$8.50", "/img/menu-egg-ham-cheese.jpg", false, 5),

        new MenuItem("ham-cheese-rollito", "Rollito de Jamón y Queso", "Ham and Cheese Rollito",
            "Sandwiches", "Sandwiches",
            "Jamón y queso derretido envueltos en un rollo.",
            "Ham and melted cheese wrapped in a roll.",
            "Masa, jamón, queso",
            "Dough, ham, cheese",
            "$4.75", "/img/menu-ham-cheese-rollito.jpg", false, 6),

        new MenuItem("ham-cheese-sandwich", "Sándwich de Jamón y Queso", "Ham and Cheese Sandwich",
            "Sandwiches", "Sandwiches",
            "Jamón y queso derretido entre pan fresco para un clásico satisfactorio.",
            "Sliced ham and melted cheese layered between fresh bread for a classic, satisfying bite.",
            "Pan fresco, jamón, queso",
            "Fresh bread, ham, cheese",
            "$8.25", "/img/menu-ham-cheese-sandwich.jpg", false, 7),

        new MenuItem("ham-cheese-croissant", "Croissant de Jamón y Queso", "Ham and Cheese Croissant",
            "Sandwiches", "Sandwiches",
            "Croissant hojaldrado relleno de sabroso jamón y queso derretido.",
            "Flaky croissant filled with savory ham and melted cheese for a delightful, buttery treat.",
            "Croissant, jamón, queso",
            "Croissant, ham, cheese",
            "$8.25", "/img/menu-ham-cheese-croissant.jpg", false, 8),

        new MenuItem("croquetas-preparada", "Croquetas Preparadas", "Croquetas Preparada",
            "Sandwiches", "Sandwiches",
            "Croquetas en un sándwich, una deliciosa fusión de sabores en cada bocado.",
            "Savory croquettes nestled in a sandwich, offering a delightful fusion of flavors in every bite.",
            "Pan, croquetas de jamón o pollo",
            "Bread, ham or chicken croquettes",
            "$10.00", "/img/menu-croquetas-preparada.jpg", false, 9),

        new MenuItem("bacon-egg-sandwich", "Sándwich de Bacon y Huevo", "Bacon and Egg Sandwich",
            "Sandwiches", "Sandwiches",
            "Bacon crujiente y huevo en un sándwich tostado.",
            "Crisp bacon and egg on a toasted sandwich.",
            "Pan tostado, bacon, huevo",
            "Toasted bread, bacon, egg",
            "$7.25", "/img/menu-bacon-egg-sandwich.jpg", false, 10),

        new MenuItem("galletas-cubanas", "Galletas Cubanas", "Galletas Cubanas",
            "Sandwiches", "Sandwiches",
            "Galletas cubanas clásicas con un crujido ligero y delicado.",
            "Classic Cuban crackers with a crisp, light crunch.",
            "Harina, manteca, sal",
            "Flour, lard, salt",
            "$3.60", "/img/menu-galletas-cubanas.jpg", false, 11),

        new MenuItem("palitroques", "Palitroques", "Palitroques",
            "Sandwiches", "Sandwiches",
            "Palitos de pan largos y delgados con un crujido sabroso.",
            "Long, slender breadsticks with a crisp bite.",
            "Harina, levadura, sal, manteca",
            "Flour, yeast, salt, lard",
            "$3.60", "/img/menu-palitroques.jpg", false, 12),

        new MenuItem("salami-cheese-rollito", "Rollito de Salami y Queso", "Salami and Cheese Rollito",
            "Sandwiches", "Sandwiches",
            "Salami finamente cortado y queso envueltos en un rollo crujiente.",
            "Thinly sliced salami and melted cheese wrapped in a crispy roll.",
            "Masa, salami, queso",
            "Dough, salami, cheese",
            "$4.75", "/img/menu-salami-cheese-rollito.jpg", false, 13),

        new MenuItem("turkey-cheese-sandwich", "Sándwich de Pavo y Queso", "Turkey and Cheese Sandwich",
            "Sandwiches", "Sandwiches",
            "Sabroso sándwich de pavo y queso, perfecto para una comida rápida y satisfactoria.",
            "Savory turkey and cheese sandwich, perfect for a quick and satisfying meal.",
            "Pan, pavo, queso",
            "Bread, turkey, cheese",
            "$7.00", "/img/menu-turkey-cheese-sandwich.jpg", false, 14),

        new MenuItem("pan-cubano", "Pan Cubano", "Pan Cubano",
            "Sandwiches", "Sandwiches",
            "Pan cubano tradicional, perfecto para sándwiches o como acompañante, con interior suave y corteza crujiente.",
            "Traditional Cuban bread, perfect for sandwiches or as a side, with a soft interior and crispy crust.",
            "Harina, levadura, sal, manteca, agua",
            "Flour, yeast, salt, lard, water",
            "$2.85", "/img/menu-pan-cubano.jpg", false, 15),

        new MenuItem("pan-cubano-entero", "Pan Cubano Entero con Mantequilla", "Pan Cubano (Entero) con Mantequilla",
            "Sandwiches", "Sandwiches",
            "Pan cubano entero con mantequilla, corteza fina y crujiente e interior suave.",
            "Whole Cuban bread loaf with butter, thin crisp crust and a soft interior.",
            "Pan cubano entero, mantequilla",
            "Whole Cuban bread, butter",
            "$8.50", "/img/menu-pan-cubano-entero.jpg", false, 16),

        new MenuItem("empanadas-beef", "Empanadas (Carne)", "Empanadas (Beef)",
            "Aperitivo", "Appetizers",
            "Tierna carne de res envuelta en una masa crujiente.",
            "Tender beef wrapped in a crispy pastry.",
            "Masa, carne molida, cebolla, ajo, comino, sal",
            "Dough, ground beef, onion, garlic, cumin, salt",
            "$2.80", "/img/menu-empanadas-beef.jpg", true, 17),

        new MenuItem("ham-croquettes", "Croquetas de Jamón", "Ham Croquettes",
            "Aperitivo", "Appetizers",
            "Crujientes bocados rellenos de sabroso jamón.",
            "Crispy bites filled with savory ham.",
            "Jamón, bechamel, pan rallado, huevo",
            "Ham, béchamel, breadcrumbs, egg",
            "$1.50", "/img/menu-ham-croquettes.jpg", true, 18),

        new MenuItem("papas-rellenas", "Papas Rellenas", "Papas Rellenas",
            "Aperitivo", "Appetizers",
            "Papas rellenas con un sabroso relleno.",
            "Stuffed potatoes with a savory filling.",
            "Papa, carne molida, sofrito, pan rallado, huevo",
            "Potato, ground beef, sofrito, breadcrumbs, egg",
            "$2.50", "/img/menu-papas-rellenas.jpg", false, 19),

        new MenuItem("tira-bocaditos", "Tira de Bocaditos", "Tira de Bocaditos",
            "Aperitivo", "Appetizers",
            "Crujientes bocados de masa rellenos de sabores deliciosos.",
            "Crispy pastry bites filled with savory flavors.",
            "Pan suave, pasta de bocaditos",
            "Soft bread, sandwich spread",
            "$4.50", "/img/menu-tira-bocaditos.jpg", false, 20),

        new MenuItem("pasta-bocaditos", "Pasta de Bocaditos (1 Libra)", "Pasta de Bocaditos (1 Pound)",
            "Aperitivo", "Appetizers",
            "Una libra de pasta cremosa para untar, ideal para preparar bocaditos en casa.",
            "Ham spread. One pound of creamy spread, ideal for making finger sandwiches at home.",
            "Jamón, queso crema, mayonesa, especias",
            "Ham, cream cheese, mayonnaise, spices",
            "$13.00", "/img/menu-pasta-bocaditos.jpg", false, 21),

        new MenuItem("empanada-queso", "Empanada de Queso", "Empanada de Queso (Cheese)",
            "Aperitivo", "Appetizers",
            "Sabrosa masa rellena de queso derretido.",
            "Savory pastry filled with melted cheese.",
            "Masa, queso",
            "Dough, cheese",
            "$2.80", "/img/menu-empanada-queso.jpg", false, 22),

        new MenuItem("empanadas-pollo", "Empanadas de Pollo", "Empanadas de Pollo (Chicken)",
            "Aperitivo", "Appetizers",
            "Tierno pollo envuelto en una masa hojaldrada.",
            "Tender chicken wrapped in a flaky pastry.",
            "Masa, pollo, sofrito, especias",
            "Dough, chicken, sofrito, spices",
            "$2.80", "/img/menu-empanadas-pollo.jpg", false, 23),

        new MenuItem("shake-strawberry", "Batido de Fresa", "Strawberry Shake",
            "Batidos", "Shakes",
            "Refrescante batido de fresa, preparado con agua o leche.",
            "Refreshing strawberry shake, made with water or milk.",
            "Fresa, agua o leche, azúcar, hielo",
            "Strawberry, water or milk, sugar, ice",
            "$7.00", "/img/menu-shake-strawberry.jpg", false, 24),

        new MenuItem("shake-mango", "Batido de Mango", "Mango Shake",
            "Batidos", "Shakes",
            "Cremoso batido de mango, preparado con leche o agua.",
            "Creamy mango shake, made with milk or water.",
            "Mango, leche o agua, azúcar, hielo",
            "Mango, milk or water, sugar, ice",
            "$7.00", "/img/menu-shake-mango.jpg", false, 25),

        new MenuItem("shake-trigo", "Batido de Trigo", "Trigo Shake",
            "Batidos", "Shakes",
            "Tradicional batido de trigo cubano, preparado con leche.",
            "Traditional Cuban wheat shake, made with milk.",
            "Trigo, leche, azúcar, hielo",
            "Wheat, milk, sugar, ice",
            "$7.00", "/img/menu-shake-trigo.jpg", false, 26),

        new MenuItem("shake-passion-fruit", "Batido de Maracuyá", "Passion Fruit Shake",
            "Batidos", "Shakes",
            "Batido de maracuyá con un toque tropical, preparado con leche o agua.",
            "Passion fruit shake with a tropical touch, made with milk or water.",
            "Maracuyá, leche o agua, azúcar, hielo",
            "Passion fruit, milk or water, sugar, ice",
            "$7.00", "/img/menu-shake-passion-fruit.jpg", false, 27),

        new MenuItem("shake-papaya", "Batido de Papaya", "Papaya Shake",
            "Batidos", "Shakes",
            "Suave batido de papaya, preparado con leche o agua.",
            "Smooth papaya shake, made with milk or water.",
            "Papaya, leche o agua, azúcar, hielo",
            "Papaya, milk or water, sugar, ice",
            "$7.00", "/img/menu-shake-papaya.jpg", false, 28),

        new MenuItem("shake-blackberry", "Batido de Mora", "Blackberry Shake",
            "Batidos", "Shakes",
            "Batido de mora, preparado con leche o agua.",
            "Blackberry shake, made with milk or water.",
            "Mora, leche o agua, azúcar, hielo",
            "Blackberry, milk or water, sugar, ice",
            "$7.00", "/img/menu-shake-blackberry.jpg", false, 29),

        new MenuItem("shake-guanabana", "Batido de Guanábana", "Guanabana Shake",
            "Batidos", "Shakes",
            "Exótico batido de guanábana, preparado con leche o agua.",
            "Exotic soursop shake, made with milk or water.",
            "Guanábana, leche o agua, azúcar, hielo",
            "Soursop, milk or water, sugar, ice",
            "$7.00", "/img/menu-shake-guanabana.jpg", false, 30),

        new MenuItem("pachi-pachi", "Pachi Pachi (Guayaba y Queso)", "Pachi Pachi (Guava and Cheese)",
            "Pasteles", "Pastries",
            "Dulce pastel de guayaba y queso.",
            "Sweet guava and cheese pastry.",
            "Hojaldre, pasta de guayaba, queso crema",
            "Puff pastry, guava paste, cream cheese",
            "$2.00", "/img/menu-pachi-pachi.jpg", false, 31),

        new MenuItem("cuban-masareal", "Masa Real Cubana", "Cuban Masareal",
            "Pasteles", "Pastries",
            "Tradicional pastel cubano con capas de pasta de guayaba y masa dulce, un delicioso sabor tropical.",
            "A traditional Cuban pastry with layers of guava paste and sweet dough, offering a delightful tropical taste.",
            "Harina, azúcar, mantequilla, pasta de guayaba",
            "Flour, sugar, butter, guava paste",
            "$2.00", "/img/menu-cuban-masareal.jpg", false, 32),

        new MenuItem("pastel-guava-cheese", "Pastel de Guayaba y Queso", "Pastel Guava And Cheese",
            "Pasteles", "Pastries",
            "Dulce pastel relleno de guayaba y queso derretido.",
            "Sweet pastry filled with guava and melted cheese.",
            "Hojaldre, pasta de guayaba, queso",
            "Puff pastry, guava paste, cheese",
            "$1.80", "/img/menu-pastel-guava-cheese.jpg", false, 33),

        new MenuItem("pastel-carne", "Pastel de Carne", "Pastel de Carne (Beef)",
            "Pasteles", "Pastries",
            "Tierna carne en un pastel tradicional. (Si desea más de 20 unidades, contacte a la panadería con anticipación.)",
            "Tender beef in a traditional pastry. (If you want more than 20 items, please call the bakery before.)",
            "Hojaldre, carne molida, sofrito, especias",
            "Puff pastry, ground beef, sofrito, spices",
            "$2.00", "/img/menu-pastel-carne.jpg", false, 34),

        new MenuItem("pastel-guava", "Pastel de Guayaba", "Pastel Guava",
            "Pasteles", "Pastries",
            "Dulce pastel relleno de guayaba.",
            "Sweet pastry filled with guava.",
            "Hojaldre, pasta de guayaba",
            "Puff pastry, guava paste",
            "$1.70", "/img/menu-pastel-guava.jpg", false, 35),

        new MenuItem("pastel-espinaca", "Pastel de Espinaca", "Pastel de Espinacas (Spinach)",
            "Pasteles", "Pastries",
            "Sabrosa masa rellena de espinaca.",
            "Savoury pastry filled with spinach.",
            "Hojaldre, espinaca, queso crema",
            "Puff pastry, spinach, cream cheese",
            "$3.65", "/img/menu-pastel-espinaca.jpg", false, 36),

        new MenuItem("pastel-coco", "Pastel de Coco", "Pastel de Coco",
            "Pasteles", "Pastries",
            "Postre de masa con coco.",
            "Coconut pastry dessert.",
            "Hojaldre, coco, azúcar",
            "Puff pastry, coconut, sugar",
            "$2.00", "/img/menu-pastel-coco.jpg", false, 37),

        new MenuItem("capuchinos", "Capuchinos", "Capuchinos",
            "Postres Cubanos", "Cuban Desserts",
            "Tradicional postre cubano bañado en almíbar, suave y delicado.",
            "Traditional Cuban dessert.",
            "Yema de huevo, azúcar, almíbar",
            "Egg yolk, sugar, syrup",
            "$2.75", "/img/menu-capuchinos.jpg", false, 38),

        new MenuItem("cabezotes", "Cabezotes", "Cabezotes",
            "Postres Cubanos", "Cuban Desserts",
            "Tradicional postre cubano de masa dulce.",
            "Traditional Cuban dessert.",
            "Harina, azúcar, huevo, almíbar",
            "Flour, sugar, egg, syrup",
            "$2.75", "/img/menu-cabezotes.jpg", false, 39),

        new MenuItem("senoritas-dulce-leche", "Señoritas Dulce de Leche", "Señoritas Dulce de Leche",
            "Postres Cubanos", "Cuban Desserts",
            "Postre cremoso disponible en sabor dulce de leche o vainilla.",
            "Rich, creamy dessert available in Dulce de Leche or vanilla flavors.",
            "Hojaldre, dulce de leche o crema de vainilla",
            "Puff pastry, dulce de leche or vanilla cream",
            "$2.80", "/img/menu-senoritas-dulce-leche.jpg", false, 40),

        new MenuItem("cuban-pudin", "Pudín Cubano", "Cuban Pudin",
            "Postres Cubanos", "Cuban Desserts",
            "Tradicional postre cubano de textura rica y cremosa con un toque de caramelo.",
            "Traditional Cuban dessert with a rich, creamy texture and a hint of caramel sweetness.",
            "Pan, leche, huevo, azúcar, pasas, caramelo",
            "Bread, milk, egg, sugar, raisins, caramel",
            "$2.50", "/img/menu-cuban-pudin.jpg", false, 41),

        new MenuItem("cuban-flan", "Flan Cubano", "Cuban Flan",
            "Postres Cubanos", "Cuban Desserts",
            "Sedoso y suave flan con cubierta de caramelo, una clásica experiencia de postre cubano.",
            "Silky, smooth flan with a caramelized top, offering a classic Cuban dessert experience.",
            "Huevo, leche condensada, leche evaporada, azúcar, vainilla",
            "Egg, condensed milk, evaporated milk, sugar, vanilla",
            "$3.75", "/img/menu-cuban-flan.jpg", false, 42),

        new MenuItem("brazo-gitano-slice", "Slice de Brazo Gitano", "Slice Brazo Gitano",
            "Postres Cubanos", "Cuban Desserts",
            "Tradicional pastel cubano relleno de crema dulce y enrollado con un toque delicado.",
            "Traditional Cuban pastry filled with sweet cream and rolled with a delicate touch.",
            "Bizcocho, crema dulce",
            "Sponge cake, sweet cream",
            "$3.15", "/img/menu-brazo-gitano-slice.jpg", false, 43),

        new MenuItem("marquesitas", "Marquesitas (Vainilla o Chocolate)", "Marquesitas (Vanilla or Chocolate)",
            "Postres Cubanos", "Cuban Desserts",
            "Finas y crujientes obleas servidas con un toque de rica vainilla o chocolate.",
            "Thin, crispy wafers served with a side of rich vanilla or chocolate.",
            "Oblea, crema de vainilla o chocolate",
            "Wafer, vanilla or chocolate cream",
            "$2.50", "/img/menu-marquesitas.jpg", false, 44),

        new MenuItem("cheese-cake-slice", "Cheese Cake", "Cheese Cake",
            "Postres Cubanos", "Cuban Desserts",
            "Rico y cremoso postre de textura aterciopelada.",
            "Rich and creamy dessert with a velvety texture.",
            "Queso crema, azúcar, huevo, galleta, mantequilla",
            "Cream cheese, sugar, egg, cookie, butter",
            "$3.25", "/img/menu-cheese-cake-slice.jpg", false, 45),

        new MenuItem("tortica-cubana", "Tortica Cubana", "Tortica Cubana",
            "Postres Cubanos", "Cuban Desserts",
            "Tradicional dulce cubano de sabor rico y delicioso.",
            "Traditional Cuban dessert with a sweet and rich flavor.",
            "Harina, manteca, azúcar, vainilla",
            "Flour, lard, sugar, vanilla",
            "$2.00", "/img/menu-tortica-cubana.jpg", false, 46),

        new MenuItem("brazo-gitano-dulce-leche", "Slice Brazo Gitano (Dulce de Leche)", "Slice Brazo Gitano (Dulce de Leche)",
            "Postres Cubanos", "Cuban Desserts",
            "Bizcocho enrollado relleno de dulce de leche.",
            "Rolled sponge cake filled with dulce de leche.",
            "Bizcocho, dulce de leche",
            "Sponge cake, dulce de leche",
            "$3.80", "/img/menu-brazo-gitano-dulce-leche.jpg", false, 47),

        new MenuItem("fresh-orange-juice", "Jugo de Naranja Natural", "Fresh Orange Juice",
            "Jugos", "Juices",
            "Jugo recién exprimido de naranjas.",
            "Freshly squeezed juice from oranges.",
            "Naranja",
            "Orange",
            "$8.00", "/img/menu-fresh-orange-juice.jpg", true, 48),

        new MenuItem("coffee-to-go-leche", "Café para Llevar (Café con Leche)", "Coffee to Go (Cafe con leche)",
            "Cafés", "Coffees",
            "Café con leche para llevar. 45 minutos para estar listo.",
            "Coffee with milk to go. 45 minutes to be ready.",
            "Café cubano, leche",
            "Cuban coffee, milk",
            "$41.00", "/img/menu-coffee-to-go-leche.jpg", false, 49),

        new MenuItem("coffee-to-go-american", "Café para Llevar (Café Americano)", "Coffee to Go (American Coffee)",
            "Cafés", "Coffees",
            "Café recién hecho para llevar.",
            "Freshly brewed coffee to take on the go.",
            "Café americano",
            "American coffee",
            "$30.00", "/img/menu-coffee-to-go-american.jpg", false, 50),

        new MenuItem("cafe-leche-12oz", "Café con Leche (12oz)", "Café w/ Leche (12oz)",
            "Cafés", "Coffees",
            "Clásico café con leche cubano en vaso de 12 onzas.",
            "Classic Cuban coffee with milk in a 12oz cup.",
            "Café cubano, leche",
            "Cuban coffee, milk",
            "$4.25", "/img/menu-cafe-leche-12oz.jpg", false, 51),

        new MenuItem("chocolate-12oz", "Chocolate Caliente (12oz)", "Chocolate (12oz)",
            "Cafés", "Coffees",
            "Rico y decadente chocolate caliente.",
            "Rich and decadent hot chocolate.",
            "Chocolate, leche, azúcar",
            "Chocolate, milk, sugar",
            "$4.25", "/img/menu-chocolate-12oz.jpg", false, 52),

        new MenuItem("ice-latte-16oz", "Ice Latte (16oz)", "Ice Latte (16oz)",
            "Cafés", "Coffees",
            "Refrescante latte helado en vaso de 16 onzas.",
            "Refreshing iced latte in a 16oz cup.",
            "Café espresso, leche, hielo",
            "Espresso, milk, ice",
            "$5.00", "/img/menu-ice-latte-16oz.jpg", true, 53),

        new MenuItem("tea-12oz", "Té (12oz)", "Tea (12oz)",
            "Cafés", "Coffees",
            "Té recién hecho servido en vaso de 12 onzas.",
            "Hot brewed tea served in a 12oz cup.",
            "Té, agua",
            "Tea, water",
            "$2.60", "/img/menu-tea-12oz.jpg", false, 54),

        new MenuItem("american-coffee-12oz", "Café Americano (12oz)", "American Coffee (12oz)",
            "Cafés", "Coffees",
            "Café americano en vaso de 12 onzas.",
            "American coffee in a 12oz cup.",
            "Café americano, agua",
            "American coffee, water",
            "$2.50", "/img/menu-american-coffee-12oz.jpg", false, 55),

        new MenuItem("espresso", "Espresso", "Espresso",
            "Cafés", "Coffees",
            "Intenso shot de espresso cubano.",
            "Intense Cuban espresso shot.",
            "Café espresso",
            "Espresso coffee",
            "$2.00", "/img/menu-espresso.jpg", false, 56),

        new MenuItem("cortadito", "Cortadito", "Cortadito",
            "Cafés", "Coffees",
            "Rico y suave café estilo espresso cortado con leche.",
            "Rich and smooth espresso-style coffee.",
            "Café espresso, leche",
            "Espresso, milk",
            "$2.60", "/img/menu-cortadito.jpg", false, 57),

        new MenuItem("capuchino-12oz", "Capuchino (12oz)", "Capuchino (12 oz)",
            "Cafés", "Coffees",
            "Espresso con leche vaporizada y una ligera capa de espuma, servido en vaso de 12 onzas.",
            "Espresso with steamed milk and a light layer of foam, served in a 12oz cup.",
            "Café espresso, leche vaporizada, espuma",
            "Espresso, steamed milk, foam",
            "$4.75", "/img/menu-capuchino-12oz.jpg", false, 58),

        new MenuItem("regular-sodas", "Sodas Regulares", "Regular Sodas",
            "Bebidas", "Drinks",
            "Variedad de sodas: Coca Cola, Sunkist, Materva, Jupiña.",
            "Variety of sodas: Coca Cola, Sunkist, Materva, Jupiña.",
            "Refresco embotellado",
            "Bottled soda",
            "$2.00", "/img/menu-regular-sodas.jpg", false, 59),

        new MenuItem("malta-large", "Malta (Grande)", "Malta (Large)",
            "Bebidas", "Drinks",
            "Bebida dulce y refrescante de malta.",
            "A sweet and refreshing drink.",
            "Malta",
            "Malt drink",
            "$2.25", "/img/menu-malta-large.jpg", false, 60),

        new MenuItem("malta-small", "Malta (Pequeña)", "Malta (Small)",
            "Bebidas", "Drinks",
            "Bebida dulce y refrescante de malta.",
            "Sweet, refreshing drink from Malta.",
            "Malta",
            "Malt drink",
            "$1.50", "/img/menu-malta-small.jpg", false, 61),

        new MenuItem("water", "Agua", "Water",
            "Bebidas", "Drinks",
            "Refrescante e hidratante.",
            "Refreshing and hydrating.",
            "Agua embotellada",
            "Bottled water",
            "$1.60", "/img/menu-water.jpg", false, 62),

        new MenuItem("snapple", "Snapple", "Snapple",
            "Bebidas", "Drinks",
            "Refrescante bebida Snapple.",
            "Refreshing Snapple drink.",
            "Bebida embotellada",
            "Bottled drink",
            "$2.75", "/img/menu-snapple.jpg", false, 63),

        new MenuItem("goya-juice", "Jugo Goya", "Goya Juice",
            "Bebidas", "Drinks",
            "Jugo Goya en variedad de sabores tropicales.",
            "Goya juice in a variety of tropical flavors.",
            "Jugo de fruta",
            "Fruit juice",
            "$2.30", "/img/menu-goya-juice.jpg", false, 64),

        new MenuItem("pernil-asado", "Pernil Asado (Ordenar 48hr Antes)", "Pernil Asado (Order 48 hr Before)",
            "Pernil Asado", "Roast Pork",
            "Pernil de cerdo asado al estilo cubano, marinado y cocido lentamente. Ordenar con 48 horas de anticipación. 1 pernil asado.",
            "Cuban-style roasted pork shoulder, marinated and slow-cooked. Order 48 hours in advance. 1 roast pork.",
            "Pernil de cerdo, mojo cubano, ajo, naranja agria, especias",
            "Pork shoulder, Cuban mojo, garlic, sour orange, spices",
            "$47.79", "/img/menu-pernil-asado.jpg", true, 65)
        );

        repo.saveAll(items);
        System.out.println("[MenuSeeder] " + items.size() + " productos del menu cargados a la base de datos.");
    }
}
